name: Create Next Documentation

on:
    push:
      branches:
        - 'main'
    schedule:
      # * is a special character in YAML so you have to quote this string
      # Run an update everyday at 5:30 am to keep next updated 
      - cron:  '30 5 * * *'
env:
  SDK_REPO : luci-ros2-sdk
  MESSAGE_REPO : luci-ros2-msgs
  GRPC_REPO : luci-ros2-grpc
  TRANSFORMS_REPO : luci-ros2-transforms
  KEYBOARD_REPO : luci-ros2-keyboard-teleop
  THIRD_PARTY_REPO : luci-ros2-third-party
  DOCS_REPO : luci-ros2-sdk-docs

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Setup npm
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Docusaurus
        run: |
          npm install --global docusaurus-init
          docusaurus-init

      - name: Checkout SDK Branch
        uses: actions/checkout@v3
        with:
          ref: "main"
          path: ${{env.SDK_REPO}}

      - name: Checkout grpc repo
        uses: actions/checkout@v3
        with:
          repository: lucimobility/luci-ros2-grpc
          ref: main
          path: ${{env.GRPC_REPO}}
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Checkout msg repo
        uses: actions/checkout@v3
        with:
          repository: lucimobility/luci-ros2-msgs
          ref: main
          path: ${{env.MESSAGE_REPO}}
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Checkout transforms repo
        uses: actions/checkout@v3
        with:
          repository: lucimobility/luci-ros2-transforms
          ref: main
          path: ${{env.TRANSFORMS_REPO}}
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Checkout keyboard repo
        uses: actions/checkout@v3
        with:
          repository: lucimobility/luci-ros2-keyboard-teleop
          ref: main
          path: ${{env.KEYBOARD_REPO}}
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Checkout third party repo
        uses: actions/checkout@v3
        with:
          repository: lucimobility/luci-ros2-third-party
          ref: main
          path: ${{env.THIRD_PARTY_REPO}}
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Checkout docs repo
        uses: actions/checkout@v3
        with:
          repository: lucimobility/luci-ros2-sdk-docs
          ref: main
          path: ${{env.DOCS_REPO}}
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Copy documentation to Doc repo
        run: |
          rm -rf ${{env.DOCS_REPO}}/source_files/3_Packages/
          rm -rf ${{env.DOCS_REPO}}/source_files/2_How-To/

          mkdir ${{env.DOCS_REPO}}/source_files/3_Packages

          cp -r ${{env.GRPC_REPO}}/docs/ ${{env.DOCS_REPO}}/source_files/3_Packages/'GRPC Interface'
          cp -r ${{env.MESSAGE_REPO}}/docs/ ${{env.DOCS_REPO}}/source_files/3_Packages/'Messages'
          cp -r ${{env.TRANSFORMS_REPO}}/docs/ ${{env.DOCS_REPO}}/source_files/3_Packages/Transforms
          cp -r ${{env.KEYBOARD_REPO}}/docs/ ${{env.DOCS_REPO}}/source_files/3_Packages/'Basic Teleop'
          cp -r ${{env.THIRD_PARTY_REPO}}/docs/ ${{env.DOCS_REPO}}/source_files/3_Packages/'Third Party'
          cp -r ${{env.SDK_REPO}}/docs/ ${{env.DOCS_REPO}}/source_files/2_How-To

      - name: Generate Static site
        run: |
          cd ${{env.DOCS_REPO}}
          rm -rf docs
          npm run build
          mv build docs

      - name: Commit docs to docs repo
        run: |
          cd ${{env.DOCS_REPO}}
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -am "Updated Docs"
          echo ${{ github.ref_name }}

      - name: Push changes to docs repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          repository: lucimobility/luci-ros2-sdk-docs
          branch: main
          directory: ${{env.DOCS_REPO}}
        
